fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "no-reply@yourdomain.com"
        sender_name: "Your App"
    service:
        mailer: app.mailer