framework:
  secret: '%env(APP_SECRET)%'
  form: true
  csrf_protection: true
  validation: {
    enable_attributes: true
  }
  trusted_hosts: ~
  session:
    handler_id: null
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
  fragments: true
  http_method_override: true
  assets: true
  php_errors:
    log: true