<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccountTransactionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountTransactionsRepository extends EntityRepository
{

  public function paidThisMonth()
  {
    $today = new \DateTime();
    return $this
            ->createQueryBuilder('at')
            ->select('at')
            ->where('MONTH(at.createdAt) = MONTH(:today)')
            ->andWhere('at.amount < 0')
            ->setParameter(':today', $today->format('Y-m-d'))
            ->getQuery()
            ->getResult();
  }

}
