<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AccountTransactionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountTransactionsRepository extends EntityRepository
{

  public function issuedThisMonth()
  {
    $today = new \DateTime();
    return $this
            ->createQueryBuilder('at')
            ->select('at')
            ->where('MONTH(at.issuedAt) = MONTH(:today)')
            ->andWhere('YEAR(at.issuedAt) = YEAR(:today)')
            ->andWhere('at.amount > 0')
            ->setParameter(':today', $today->format('Y-m-d'))
            ->getQuery()
            ->getResult();
  }

  public function queryAccountRange($account)
  {
    return $this
            ->createQueryBuilder('at')
            ->select('MIN(at.issuedAt) as rangeStart, MAX(at.issuedAt) as rangeEnd')
            ->where('at.account = :account')
            ->groupBy('at.account')
            ->setParameter(':account', $account)
            ->getQuery()
            ->getOneOrNullResult();
  }

  public function queryAccountFromTo($account, $from, $to)
  {
    return $this
            ->createQueryBuilder('at')
            ->where('at.account = :account')
            ->andWhere('at.issuedAt  >= :from')
            ->andWhere('at.issuedAt <= :to')
            ->setParameter(':account', $account)
            ->setParameter(':from', $from)
            ->setParameter(':to', $to)
            ->getQuery()
            ->getResult();
  }

}
