<?php

namespace AppBundle\Repository;

/**
 * BalanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BalanceRepository extends \Doctrine\ORM\EntityRepository
{

  public function findLast()
  {
    return $this
            ->createQueryBuilder('b')
            ->select('b')
            ->orderBy('b.balanceAt', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult()
    ;
  }

}
