<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CostOfLife;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * CostOfLifeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostOfLifeRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, CostOfLife::class);
    }

    public function sumCostOfLife()
    {
        return $this
            ->createQueryBuilder('col')
            ->select('SUM(col.value)/100 as cost')
            ->getQuery()
            ->getSingleResult();
    }
}
