<?php

namespace AppBundle\Repository;

/**
 * DashboardTaskListsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DashboardTaskListsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->createQueryBuilder('dtl')
          ->select('dtl, tl')
          ->leftJoin('dtl.taskList', 'tl')
          ->getQuery()
          ->getResult();
    }

    public function findAllTaskLists()
    {
        $queryString = "SELECT tl, dtl.id FROM AppBundle:TaskLists tl " .
          "LEFT JOIN AppBundle:DashboardTaskLists dtl WITH dtl.taskList = tl.id";

        return $this->getEntityManager()->createQuery($queryString)
          ->getResult();
    }
}
