<?php

namespace AppBundle\Repository;

use AppBundle\Entity\DashboardTaskLists;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * DashboardTaskListsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DashboardTaskListsRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, DashboardTaskLists::class);
    }
    public function findAllTaskLists()
    {
        return $this->getEntityManager()->createQuery('SELECT tl, dtl.id FROM AppBundle:TaskLists tl LEFT JOIN AppBundle:DashboardTaskLists dtl WITH dtl.taskList = tl.id  ')
            ->getResult();
    }
}
