<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DaysRepository extends EntityRepository
{

    public function getActiveCards()
    {
        return $this->createQueryBuilder('d')
                        ->where('d.complete = 0')
                        ->orWhere('d.deadline >= CURRENT_TIMESTAMP()')
                        ->orderBy('d.deadline', 'ASC')
                        ->getQuery()
                        ->getResult();
    }

    public function getArchiveCards()
    {
        return $this->createQueryBuilder('d')
                        ->where('d.complete = 1')
                        ->andWhere('d.deadline < CURRENT_TIMESTAMP()')
                        ->orderBy('d.deadline', 'ASC')
                        ->getQuery()
                        ->getResult();
    }

}
