<?php

namespace AppBundle\Repository;

/**
 * PriceRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRateRepository extends \Doctrine\ORM\EntityRepository
{
}
