<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Rate;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * RateRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Rate::class);
    }
    public function getActiveRates()
    {
        return $this
            ->createQueryBuilder('r')
            ->where('r.active = true')
            ->getQuery()
            ->getResult();
    }
}
