<?php

namespace AppBundle\Repository;

/**
 * RecurrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecurrRepository extends \Doctrine\ORM\EntityRepository
{
}
