<?php

namespace AppBundle\Repository;

/**
 * ScratchPadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScratchPadRepository extends \Doctrine\ORM\EntityRepository
{
}
