<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * transactionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionsRepository extends EntityRepository
{

  public function findDailyAverage()
  {
    return $this
            ->createQueryBuilder('txn')
            ->select('AVG(txn.value) as value')
            ->where('txn.name = \'Daily\'')
            ->getQuery()
            ->getOneOrNullResult();
  }

  public function findLastDaily()
  {
    return $this
            ->createQueryBuilder('txn')
            ->where('txn.name = \'Daily\'')
            ->orderBy("txn.date", "DESC")
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
  }

  public function findLast()
  {
    return $this
            ->createQueryBuilder('txn')
            ->orderBy("txn.date", "DESC")
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
  }

}
