<?php

namespace AppBundle\Repository;

/**
 * WorkLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkLogRepository extends \Doctrine\ORM\EntityRepository
{

  public function orderByTaskList()
  {
    return $this
            ->createQueryBuilder('wl')
            ->select('wl, t')
            ->join('wl.task', 't')
            ->orderBy('t.taskList')
            ->getQuery()
            ->getResult();
  }

}
