<?php

namespace AppBundle\Repository;

/**
 * WorkLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkLogRepository extends \Doctrine\ORM\EntityRepository
{
}
