<?php

namespace AppBundle\Repository;

/**
 * WorkLogRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkLogRepository extends \Doctrine\ORM\EntityRepository
{
    public function orderByTaskList()
    {
        return $this
            ->createQueryBuilder('wl')
            ->select('wl, t')
            ->join('wl.task', 't')
            ->orderBy('t.taskList')
            ->addOrderBy('wl.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getByTaskList($taskList)
    {
        return $this
            ->createQueryBuilder('wl')
            ->select('wl, t')
            ->join('wl.task', 't')
            ->where('t.taskList = :tasklist')
            ->setParameter(':tasklist', $taskList)
            ->addOrderBy('wl.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
