<?php

namespace App\Repository;

use App\Entity\DashboardTaskLists;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * DashboardTaskListsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DashboardTaskListsRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, DashboardTaskLists::class);
    }
    public function findAllTaskLists()
    {
return $this->createQueryBuilder('dtl')
            ->select('dtl', 'tl.id')
            ->leftJoin('dtl.taskList', 'tl')
            ->getQuery()
            ->getResult();
//        return $this->getEntityManager()->createQuery('SELECT tl, dtl.id FROM TaskLists tl LEFT JOIN DashboardTaskLists dtl WITH dtl.taskList = tl.id  ')
//            ->getResult();
    }
}
