<?php

namespace App\Repository;

use App\Entity\Notes;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * NotesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotesRepository extends ServiceEntityRepository
{

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Notes::class);
    }

    public function search($searchTerm)
    {
        return $this
          ->createQueryBuilder('n')
          ->select()
          ->where('n.note LIKE :searchTerm')
          ->setParameter(':searchTerm', '%' . $searchTerm . '%')
          ->getQuery()
          ->getResult();
    }

}
