controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


#fos_user:
#    resource: '@FOSUserBundle/Resources/config/routing/all.xml'
#    prefix: /

fos_user_security_login:
    path: /login
    controller: FOS\UserBundle\Controller\SecurityController::loginAction

fos_user_security_check:
    path: /login_check

fos_user_security_logout:
    path: /logout